export const IS_LOADING = "IS_LOADING"

export const CREATE_POKEMON = "CREATE_POKEMON"

export const GET_ALL_POKEMONS = "GET_ALL_POKEMONS"

export const GET_ALL_TYPES = "GET_ALL_TYPES"

export const GET_POKEMON_DETAILS = "GET_POKEMON_DETAILS"

export const CLEAN_POKEMON_DETAILS = "CLEAN_POKEMON_DETAILS"

export const CLEAN_POKEMON_CREATED = "CLEAN_POKEMON_CREATED"

export const SEARCH_POKEMON = "SEARCH_POKEMON"

export const FILTER_BY_TYPE = "FILTER_BY_TYPE"

export const SWAP_ORDER = "SWAP_ORDER"
