export const GET_ALL_POKEMONS = "GET_ALL_POKEMONS"

export const GET_ALL_TYPES = "GET_ALL_TYPES"

export const GET_POKEMON_DETAILS = "GET_POKEMON_DETAILS"

export const CLEAN_POKEMON_DETAILS = "CLEAN_POKEMON_DETAILS"

export const SEARCH_POKEMON = "SEARCH_POKEMON"

export const FILTER_BY_TYPE = "FILTER_BY_TYPE"

export const ORDER_BY_AZ = "ORDER_BY_AZ"
